import os
import time
import subprocess
from otherScripts.checkingFunctions import *
import math

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

pathToOPL = '"C:\Program Files\IBM\ILOG\CPLEX_Studio1271\opl\\bin\\x64_win64\oplrun.exe"'
pathToOps = "../opl_project/opl_project.ops"
# pathToMod = "../opl_project/opl_project.mod"
# pathToMod = "../opl_project/proves1.mod"
pathToMod = "../opl_project/proves2.mod"
# pathToMod = "../opl_project/proves3.mod"

def getSolution(strSolution):
    if "no solution" in strSolution:
        return []
    else:
        ll = strSolution.split()
        index = ll.index("OBJECTIVE:") + 2
        retVal = []
        while ll[index] != "<<<":
            retVal.append([int(number) for number in ll[index]])
            index += 1
        return retVal

def getParams(fileDat):
    with open(fileDat, mode='r') as f:
        d = {"solution": "UNKNOWN", "cost": math.inf}
        for line in f:
            line = line.replace("\n", "")
            if "=" in line:
                ll = line.split("=")
                name = ll[0]
                if "[" in ll[1]:
                    value = [int(number) for number in ll[1][1:-2].split(" ")]
                else:
                    value = int(ll[1][:-1])
                d[name] = value
            elif "FEASIBLE" in line:
                d["solution"] = "FEASIBLE"
            elif "INFEASIBLE" in line:
                d["solution"] = "INFEASIBLE"
            elif "COST" in line:
                d["cost"] = int(line.split()[-1])
    return d

def executeOPL(datFolder):
    listDat = list(filter(lambda f: len(f) > 5 and f[-4:] == ".dat", os.listdir(datFolder)))
    ######## provisional
    listDat = listDat[:5]
    ########
    for (i, file) in enumerate(listDat):
        print(bcolors.BOLD + str(i+1) + "/" + str(len(listDat)) + bcolors.ENDC)
        print(bcolors.BOLD + "Executing", file, bcolors.ENDC)
        pathToDat = datFolder + file
        t = time.time()
        try:
            result = subprocess.check_output(pathToOPL + " " + pathToMod + " " + pathToDat, shell=True)
        except:
            result = b"no solution"
        t = time.time() - t
        print("Time:", round(t, 2), "s")
        params = getParams(pathToDat)
        result = result.decode("utf-8")
        if result == "no solution":
            print(bcolors.UNDERLINE + "no solution" + bcolors.ENDC)
            shouldBeInfeasible = params["solution"] != "FEASIBLE"
            print("should be infeasible:", shouldBeInfeasible)
            if shouldBeInfeasible:
                print(bcolors.OKGREEN + "OK" + bcolors.ENDC)
            else:
                print(bcolors.FAIL + "FAIL" + bcolors.ENDC)
        else:
            nurses = getSolution(result)
            satConstr = answerSatisfiesConstr(nurses, params)
            cost = sum(sum(nurse) > 0 for nurse in nurses)
            print(bcolors.UNDERLINE + "solution found" + bcolors.ENDC)
            print("cost:", cost)
            costOk = cost <= params["cost"]
            print("cost ok:", costOk)
            print("constrains satisfied:", satConstr[1])
            shouldBeFeasible = params["solution"] != "INFEASIBLE"
            print("should be feasible:", shouldBeFeasible)
            if costOk and satConstr[0] and shouldBeFeasible:
                print(bcolors.OKGREEN + "OK" + bcolors.ENDC)
            else:
                print(bcolors.FAIL + "FAIL" + bcolors.ENDC)
            # print(result)
        print()

manuallyGeneratedData = "../data_generators/manuallyGeneratedData/"
autoGeneratedData = "../data_generators/autoGeneratedData/"
executeOPL(autoGeneratedData)